# Tag trigger with several tags and several scanner devices.
id: fixture_trigger_tag_multi
alias: Fixture - tag trigger multiple tags and devices
triggers:
  - trigger: tag
    tag_id:
      - A7-6B-90-5F
      - A7-6B-15-AC
    device_id:
      - 0e19cd3cf2b311ea88f469a7512c307d
      - d0609cb25f4a13922bb27d8f86e4c821
actions:
  - action: light.toggle
    target:
      entity_id: light.hallway
mode: single
